/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "led.h"
#include "uart.h"
int main(void)
{
   SystemInit();
   UartInit(9600);
   LedInit();
   char str[32];
   int choice;
   while(1)
   {
	   UartPuts("MENU\r\n");
	   UartPuts("1. Red Led On\r\n");
	   UartPuts("2. Red Led Off\r\n");
	   UartPuts("3. Blue Led On\r\n");
	   UartPuts("4. Blue Led Off\r\n");
	   UartPuts("Enter Choice: ");

	   UartGets(str);
	   sscanf(str, "%d", &choice);

	   switch(choice)
	   {
	   	   case 1:	turn_on_red_led();
	   	   	   	    UartPuts("Red Led On");
	   	   	   	   	break;
	   	   case 2:	turn_off_red_led();
	   	   	    	UartPuts("Red Led Off");
	   	   	   	   	break;
	   	   case 3:	turn_on_blue_led();
	   	  	   	    UartPuts("Blue Led On");
	   	   	   	   	break;
	   	   case 4:	turn_off_blue_led();
	   	   	   	    UartPuts("Blue Led Off");
	   		   	  	break;
	   	   default: UartPuts("invalid Choice");
	   	   	   	   	break;
	   }
   }
   return 0;

}
